[package]
authors = ["Miri Team"]
description = "An experimental interpreter for Rust MIR (core driver)."
license = "MIT/Apache-2.0"
name = "miri"
repository = "https://github.com/rust-lang/miri"
version = "0.1.0"
default-run = "miri"
edition = "2018"

[lib]
test = true # we have unit tests
doctest = false # but no doc tests

[[bin]]
name = "miri"
test = false # we have no unit tests
doctest = false # and no doc tests

[dependencies]
getrandom = { version = "0.2", features = ["std"] }
env_logger = "0.8"
log = "0.4"
shell-escape = "0.1.4"
hex = "0.4.0"
rand = "0.8"
smallvec = "1.4.2"

# A noop dependency that changes in the Rust repository, it's a bit of a hack.
# See the `src/tools/rustc-workspace-hack/README.md` file in `rust-lang/rust`
# for more information.
rustc-workspace-hack = "1.0.0"
measureme = "9.1.2"

# Enable some feature flags that dev-dependencies need but dependencies
# do not.  This makes `./miri install` after `./miri build` faster.
[target."cfg(unix)".dependencies]
libc = "0.2"

[dev-dependencies]
compiletest_rs = { version = "0.6", features = ["tmp"] }
rustc_version = "0.3"
colored = "2"

[package.metadata.rust-analyzer]
# This crate uses #[feature(rustc_private)]. 
# See https://github.com/rust-analyzer/rust-analyzer/pull/7891
rustc_private = true

[[test]]
name = "compiletest"
harness = false
