[package]
name = "ide_ssr"
version = "0.0.0"
description = "Structural search and replace of Rust code"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-analyzer/rust-analyzer"
authors = ["rust-analyzer developers"]
edition = "2018"

[lib]
doctest = false

[dependencies]
cov-mark = { version = "1.1", features = ["thread-local"] }
rustc-hash = "1.1.0"
itertools = "0.10.0"

text_edit = { path = "../text_edit", version = "0.0.0" }
syntax = { path = "../syntax", version = "0.0.0" }
ide_db = { path = "../ide_db", version = "0.0.0" }
hir = { path = "../hir", version = "0.0.0" }

[dev-dependencies]
test_utils = { path = "../test_utils" }
expect-test = "1.1"
